### ISSUE TITLE
Support case insensitive searches

### ISSUE THREAD

**Issue by kristiehowboutdat** [jest-community/jest-watch-typeahead#10]
Thanks for your hard work on this! It's been a really useful addition to my jest workflow.

My only "complaint" currently is that all of my component files are PascalCased, and I always type my watch queries in lowercase

Feature request: case-insensitive searches:

ex. `nav` AND `Nav` should show results for `components/NavBar/`, where currently, `components/NavBar` only shows up for `Nav`

Are there reasons not to do this? Happy to help with a PR if possible

**Comment by thymikee** [comment]
Sounds like a great opportunity for first PR! Would be great to get this in :)

**Comment by rogeliog** [comment]
Thanks for reporting this @kristiehowboutdat!

I think it would be awesome to solve it at a Jest level, by adding configs to plugins.

See https://github.com/jest-community/jest-watch-typeahead/issues/9#issue-328004102 for more info.

**Comment by rogeliog** [comment]
@kristiehowboutdat This should be the changes needed in Jest core to support this feature. https://github.com/facebook/jest/pull/6603

**Comment by rogeliog** [comment]
I was wrong, I apologize, my bad.

Although we would need configs eventually, it is not required for this.

![aaa](https://user-images.githubusercontent.com/574806/42245793-f389de30-7ece-11e8-8a97-38b7341a391c.gif)

I think we simply need to use the `regex` instead of the `pattern` https://github.com/jest-community/jest-watch-typeahead/blob/master/src/file_name_pattern_prompt.js#L98
